[package]
name = "mmflib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
imap = "3.0.0-alpha.6"
mail-parser = "0.4.4"
native-tls = "0.2.8"
log = "0.4.14"
anyhow = "1.0.55"
